---
- name: show version and interfaces
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: command list
      ios_command:
        commands:
        - show version
        - show ip interface brief
      register: print_output
    - debug: var=print_output.stdout_lines
